### ISSUE TITLE
Create Company Page Header

### ISSUE THREAD

**Issue by NickkTMD** [tiki/insights#18]
As a developer, to make the full company page I must first make the header component with the company name, follower count and button, and the background. 

It should match
![image](https://user-images.githubusercontent.com/14880163/169892184-57636d0f-1440-481d-89d9-318d65bde4c8.png)

Acceptance Criteria
1. Header component looks like linked image.

**Comment by NickkTMD** [comment]
![Image](https://user-images.githubusercontent.com/14880163/171741928-1a75d80a-a563-4325-9ef1-24f5ff066ee1.png)

**Comment by mike-audi** [comment]
nick to add new story for how the follow button should work

**Comment by NickkTMD** [comment]
> nick to add new story for how the follow button should work

Issue #36  - this can now be closed
