### ISSUE TITLE
create search top result component

### ISSUE THREAD

**Issue by NickkTMD** [tiki/insights#21]
As a user, when I search for an insight/company/etc on the search page, I will see the top result highlighted as shown in the image below:

![image](https://user-images.githubusercontent.com/14880163/169893039-94b0ab91-0ebd-492e-a372-c28bc13e9176.png)

As a developer I must create a component for this top result section.

Acceptance Criteria
1. Top Result component that matches image

**Comment by NickkTMD** [comment]
Done - the button color is passed into the result so we can choose/easily change for insights/companies/dashboards
![Image](https://user-images.githubusercontent.com/14880163/171287187-cbfa4806-b5a0-48f2-a16e-3c68b50736ef.png)

**Comment by mike-audi** [comment]
nick will fix sizing to match design

**Comment by NickkTMD** [comment]
Fixed
![Image](https://user-images.githubusercontent.com/14880163/171448775-a66d6409-e364-45e3-8be8-07be3af35fe9.png)
