### ISSUE TITLE
Create the project for the website using Nuxt

### ISSUE THREAD

**Issue by NickkTMD** [tiki/insights#24]
The website will be built using the Nuxt framework. We need to first create a Nuxt project for the website. 

Acceptance Criteria-
A running nuxt website that could theoretically be published

**Comment by NickkTMD** [comment]
Got it up and running.

![Image](https://user-images.githubusercontent.com/14880163/170101974-08984d9c-a161-4ad3-bd1d-b109f698a205.png)

Dev note-
Ran into a lot of issues with auto formatting with linter and such. ESLint is running but prettier seems to not be working (for things like removing semi colons)

**Comment by mike-audi** [comment]
prettier issue can be found here: #26
