### ISSUE TITLE
Make sidebar menu useable on mobile

### ISSUE THREAD

**Issue by NickkTMD** [tiki/insights#28]
The sidebar currently looks like this on mobile:
![image](https://user-images.githubusercontent.com/14880163/170543196-8b35481e-1381-4ecf-a300-456c2a9a5208.png)

As a user, I may want to check insights on mobile. The menu should have a nice, usable design. It should also be a drop down menu accessible from anywhere on the page (there should still be a menu button at the top when you scroll down).

Acceptance criteria
1. Menu looks nicer on mobile
2. Menu is easily accessible from anywhere on website while on mobile

**Comment by NickkTMD** [comment]
I have the functionality down shown here:
https://user-images.githubusercontent.com/14880163/171059365-511d41e8-eaba-4b4d-9b67-65d93735744e.mp4

But really I don't like  the design of the menu. Feel like it should be more sleek / less spaced out. Also need to think about how the site will look to users not registered/signed in, where user profile button should be on mobile, etc. Not sure of what the scope of this card should be.

**Comment by mike-audi** [comment]
no longer applicable. closing
