### ISSUE TITLE
Detect mobile users and tell them to use desktop

### ISSUE THREAD

**Issue by NickkTMD** [tiki/insights#34]
For the first release/test of the site, we don't need to support mobile users.

Need to first make a design - there was another site that did it well

There should be a nice pop up telling the user to use desktop if their screen is too small. 

Acceptance criteria-
1. When viewing site on mobile, users should see a page telling them to use desktop.

**Comment by NickkTMD** [comment]
![Image](https://user-images.githubusercontent.com/14880163/172687626-e9f4e835-a6a0-4ec9-86ba-dba2846c6df1.png)

**Comment by mike-audi** [comment]
@NickkTMD to open a story for the design

**Comment by NickkTMD** [comment]
^ #34
